monolog:
    channels:
        - 'mailer'
        - 'payment'
        - 'queue'
    handlers:
        main:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
            channels: [!event]
        mailer:
            type:     rotating_file
            path:     '%kernel.logs_dir%/mailer/mailer.log'
            level:    debug
            max_files: 10
            channels: ['mailer']
        payment:
            type:     rotating_file
            path:     '%kernel.logs_dir%/payment/payment.log'
            level:    debug
            max_files: 10
            channels: ['payment']
        queue:
            type:     rotating_file
            path:     '%kernel.logs_dir%/queue/queue.log'
            level:    debug
            max_files: 10
            channels: ['queue']