services:
    sender.send_gird:
        class: MailerBundle\SendGrid\SendGridMailer
        arguments:
            - '%send_grid_api_key%'
            - '@twig'
    mailer:
        class: MailerBundle\Mailer
        arguments:
            - '@sender.send_gird'
            - '@monolog.logger.mailer'
            - '%email_configuration%'